-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 20, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6338_QUOTE_LINES" USING 'GCG_6338_QUOTE_LINES.mkd' PAGESIZE=4096 (
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "ITEM_ID" CHAR(30),
 "PART" CHAR(20),
 "QUANTITY" DOUBLE,
 "UNIT_PRICE" DOUBLE,
 "EXTENDED_PRICE" DOUBLE,
 "QUOTE_NUMBER" CHAR(30),
 "UNIT_COST" DOUBLE,
 "TOTAL_COST" DOUBLE,
 "MATERIAL_MU" DOUBLE,
 "PRODUCTION_MU" DOUBLE,
 "MATERIAL" CHAR(20),
 "THICKNESS" DOUBLE,
 "GRADE" CHAR(30),
 "PART_LENGTH" DOUBLE,
 "PART_WIDTH" DOUBLE,
 "WEIGHT" DOUBLE,
 "RECTANGULAR_WEIGHT" DOUBLE,
 "PART_AREA" DOUBLE,
 "RECTANGULAR_AREA" DOUBLE,
 "ALLOCATE_AREA" DOUBLE,
 "MACHINE_NAME" CHAR(30),
 "WON" BIT DEFAULT '0' NOT NULL,
 "PRODUCTION_TIME" DOUBLE,
 "ALLOCATED_WEIGHT" DOUBLE,
 "PRIME_CODE" CHAR(20),
 "PRODUCTION_COST" DOUBLE );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
