-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 20, 2021
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6338_ROUTER_LINE" USING 'GCG_6338_ROUTER_LINE.mkd' PAGESIZE=4096 (
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "ITEM_ID" CHAR(30),
 "PART" CHAR(20),
 "SECONDARY_PROCESS" CHAR(50),
 "UNIT_COST" DOUBLE,
 "EXTENDED_COST" DOUBLE,
 "QUOTE" CHAR(30),
 "FIXED_TIME" DOUBLE,
 "VARIABLE_TIME" DOUBLE );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
